### ISSUE TITLE
Call to undefined function nstr_replace()

### ISSUE THREAD

**Issue by aminnairi** [Jennoss/echo.php#1]
## Expected behavior

The script should output `Helloworld` when running `php echo.php -s Hello world`.

## Current behavior

The script crashes with the following error.

```
Fatal error: Uncaught Error: Call to undefined function nstr_replace() in /usr/src/app/echo.php:28
Stack trace:
#0 {main}
  thrown in /usr/src/app/echo.php on line 28
```

## Reproduction steps

1. run `php echo.php -s Hello world`
2. See the error

**Comment by Jennoss** [comment]
Thank's ! The problem is resolved
